### ISSUE TITLE
hello world: rooms, trees and widgets

### ISSUE THREAD

**Issue by edwintorok** [sanette/bogue-tutorials#1]
Hi,

Looking through the hello world example, and pretending for a moment that I haven't yet read the docs or API for bogue, looking at just the contents of the tutorial a few questions would arise:

* does a widget have a size, does a room have a size? Can a room have a padding around a widget?

Proposed solution: I found the explanation in the existing docs quite succint, perhaps part of this could be added to the hello tutorial?
> Roughly speaking:
>    widget = content
>    layout = container

* residents, rooms, houses. But the tutorial then talks of trees: is the nesting predefined and of fixed depth, or can we have arbitrary depth nesting (with some convenient names for the lower and upper levels?)

Proposed solution:  at least according to the API the layouts can be nested arbitrarily deep, if the nesting was fixed depth I would've expected to see a non-recursive type instead: https://ocaml.org/p/bogue/latest/doc/Bogue/Layout/index.html#create-layouts-from-other-layouts.

This comment from the source code seems relevant:
https://github.com/sanette/bogue/blob/master/lib/b_layout.ml#L216-L223

I suggest a small modification to this part:
> . Thus, an element of type Layout.t can either be:
>    a true "room" (containing a single resident), or
>   a "house" containing several rooms.
>Side-note: we have here the usual construction for a tree data structure: each node is either terminal (and called a leaf, which for us are widgets), or a vertex (for us, a layout), pointing to a list of sub-nodes.
> To summarize, in Bogue, the complete GUI is simply a tree of layouts, and the leaves contain a widget.
> The trunk of the tree (our main house, if you wish), will correspond to the layout associated with the window of the GUI. In Bogue we often call this special layout the "top layout", or "top house". (Yes, this may sound weird: our tree grows top-down...) 

I think a 3rd bullet point would clarify all this: "rooms can be arbitrarily nested"

* finally I think the best way to explain the nesting and tree structure here would be visually (maybe not in the hello world example but the next one?): have a nested layout and show the boundaries of each with boxes (perhaps of different color) and have a legend showing which is the resident, room and board.

**Comment by sanette** [comment]
thanks for the comments! Indeed, when I wrote the hello world tutorial, I asked myself exactly the same questions. I was wondering whether adding more explanation to this "graph structure" would be useful at this stage (Hello world) or simply obscure the message (for a Hello world, we need a very simple message, I suppose).

That's why the comment about the graph is in a "side note" (my plan was to make these side note collapsed by default, and open only on clicking -- when I have some time to code this). Maybe we should just delete this note?

I essentially agree with all you said (in particular the visual picture of the graph) but should this be in this tutorial, or another one?

**Comment by sanette** [comment]
> * does a widget have a size, does a room have a size? Can a room have a padding around a widget?

this point is actually a bit subtle. A widget *advertizes* a size, but the layout decides which size will be displayed. So, currently, you cannot have a padding: for this you need to install the widget in a room as a resident, and then place the room within a bigger one with padding. (for instance using Layout.flat)

**Comment by edwintorok** [comment]
> thanks for the comments! Indeed, when I wrote the hello world tutorial, I asked myself exactly the same questions. I was wondering whether adding more explanation to this "graph structure" would be useful at this stage (Hello world) or simply obscure the message (for a Hello world, we need a very simple message, I suppose).

Perhaps saying that layouts can be arbitrarily nested with a link to another tutorial or the docs on the layout structure might be appropriate. You are right that going too deeply into that in a hello world may be distracting.

**Comment by sanette** [comment]
Yes, I'm going to implement your suggestions, and to try to find some time for specific "A tree of widgets and layouts" tutorial; thanks again

**Comment by sanette** [comment]
https://github.com/sanette/bogue-tutorials/commit/9f9c7d7a068070f2544be3a93ad088f2eb85fa7e
 I tried to clarify without entering too much into details... not easy

**Comment by sanette** [comment]
I think this is clarified now. Feel free to reopen.
